server:
  url: "http://10.10.10.222:5000"
  endpoint: "/api/metrics"
  timeout: 10

agent:
  name: "Windows-Server-01"
  interval: 60  # seconds
  retry_attempts: 3

telegram:
  bot_token: "8553079574:AAGUlS2j4t1khk6VwKU0fC3okki-vktSjQI"
  chat_id: "830737763"

monitoring:
  services:
    - "nginx"
    - "mysql"
    - "apache"
    - "W3SVC"
    - "MSSQLSERVER"
  disks:
    - "C:"
    - "D:"